# Generated by Django 4.0.4 on 2022-04-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCV', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(help_text='Short Bio (eg. I love cats and games)', max_length=100),
        ),
    ]
